name: Check Environment

on:
  push:
    branches: '**'

jobs:
  run_post_create_command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check folder
      run: |
        pwd
        ls -a
        cd .github
        ls -a
        cd workflows
        ls -a
        cat abc320a.rs

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rust-version: stable  # 使用する Rust のバージョンを指定

    - name: Run postCreateCommand.bash
      run: |
        bash .devcontainer/postCreateCommand.bash
        rustup install 1.70.0-x86_64-unknown-linux-gnu
    - name: check cargo-compete
      run: |
        cargo compete new abc320
        cargo member include abc320
        pwd
        cd abc320/src/bin/
        cargo build
        cargo compete test a
    - name: check formatter
      run: cargo fmt